version: "3"

volumes:
  pgdata:
    driver: local

services:

  python:
    build: 
      context: ./python
      dockerfile: Dockerfile
      args:
        - PYTHON_IMAGE_VERSION
        - OS_DEPS
        - PYTHON_OS_DEPS
        - USER_NAME
        - USER_ID
        - HOME_DIR
        - PIPENV_DEV
    env_file:
      - ./.env    
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_IMAGE_VERSION
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - backend

networks:
  backend:
    driver: bridge