version: "3"

volumes:
  redisdata:
    driver: local

services:

  python:
    build: 
      context: ./python
      dockerfile: Dockerfile
      args:
        - PYTHON_IMAGE_VERSION
        - OS_DEPS
        - PYTHON_OS_DEPS
        - USER_NAME
        - USER_ID
        - HOME_DIR
        - PIPENV_DEV
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - backend

  nodejs:
    build: 
      context: ./nodejs
      dockerfile: Dockerfile
      args:
        - NODE_IMAGE_VERSION
        - NODE_LAUNCH_COMMAND
        - OS_DEPS
        - NODE_OS_DEPS
        - USER_NAME
        - USER_ID
        - HOME_DIR
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - backend

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        - REDIS_IMAGE_VERSION
    env_file:
      - ./.env
    volumes:
      - redisdata:/data/bases
    networks:
      - backend

networks:
  backend:
    driver: bridge