version: "3"

volumes:
  pgdata:
    driver: local

services:

  nodejs:
    build: 
      context: ./nodejs
      dockerfile: Dockerfile
      args:
        - NODE_IMAGE_VERSION
        - NODE_LAUNCH_COMMAND
        - OS_DEPS
        - NODE_OS_DEPS
        - USER_NAME
        - USER_ID
        - HOME_DIR
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_IMAGE_VERSION
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - backend

networks:
  backend:
    driver: bridge