version: "3"

volumes:
  redisdata:
    driver: local

services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        - REDIS_IMAGE_VERSION
    env_file:
      - ./.env
    volumes:
      - redisdata:/data/bases
    ports:
      - 6379:6379