version: "3"

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local

services:

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        - REDIS_IMAGE_VERSION
    volumes:
      - redisdata:/data/bases
    env_file:
      - ./.env
    ports:
      - 6379:6379

  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
      args:
        - POSTGRES_IMAGE_VERSION
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"